---
engines:
  shellcheck:
    enabled: true
    checks:
      SC2034:
        enabled: false
      SC1091:
        enabled: false
      SC2154:
        enabled: false
      SC1090:
        enabled: false
ratings:
  paths:
    - git-autopull
exclude_paths:
  - "*.*"
